server.port=9090
spring.application.name=stats-server

# ??? IDE ?????????? localhost, ??? ??? ?? ? Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/stats-db
spring.datasource.username=admin
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.web=INFO
logging.level.ru.practicum=DEBUG